### ISSUE TITLE
PAGE_SIZE configuration is incorrectly reported in version 3.7.7, 

### ISSUE THREAD

**Issue by ttany** [Q1mi/Django-REST-framework-documentation#1]
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

**Comment by Q1mi** [comment]
can u show me your PAGE_SIZE conf?

**Comment by kagxin** [comment]
```python
from rest_framework.pagination import PageNumberPagination
class MyPageNumberPagination(PageNumberPagination):

    page_size_query_param = 'page_size'
    page_size = 10

class MessageView(generics.ListAPIView):
    pagination_class =  MyPageNumberPagination

http://by.ilinkin.com.cn/v1/message/?page=2&page_size=10
```

**Comment by Q1mi** [comment]
not an error, just need authentication.
